### ISSUE TITLE
GUI Plugin config

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-rviz#9]
GUI Plugin config

**Comment by Sarath18** [comment]
The visualization plugins at the moment are loaded using pluginlib. For integrating gui config for the plugin I intend to use `ignition::gui::Plugins`. But the problem is since we are exporting the plugin to pluginlib and not registering as a `gui::Plugin`, we are not able to use functionalities from the `gui::Plugin` class.

To integrate the gui config with the current implementation I manually copied the plugin instantiation code block from `gui::Plugin` and @ahcorde helped me integrate the plugin qml with `IgnCards`. The recent implementation can be found [here](https://github.com/Sarath18/ign-rviz/blob/2b67463cd1ebd8a85516a830de252dfdf31c6980/ign_rviz_plugins/src/rviz/plugins/tf_display.cpp#L71-L138).

Summarizing the current problems faced:
1. We are not able to close the plugin (might be a ancestor or context issue) but dock/undock along with minimizing of floating plugins (my branch of ign-gui) works fine.
2. By going with the current implementation, it is redundant to inherit from `gui::Plugin` can be used in the plugin base class `ignition::rviz::MessageDisplayBase` as we are not using any of its data members/functions. We can rather inherit from `QObject` (like in `master` branch).
3. This way me might also need to re-implement most of the functions resulting in a `gui::Plugin` variant for `ign-rviz` which will need maintenance on both `ign-gui` and `ign-rviz` side.

I believe this can be avoided to a great extent and there might be some way to use `gui::Plugin`. This will any new updates to `gui::Plugin` will be propagated to `ign-rviz` gui config, which I think is the whole point of modular libraries of ignition.

@chapulina can you help in figuring out the solution to the problem?
CC: @ahcorde 

This is a quick gif showing the current implementation:

<img src="https://user-images.githubusercontent.com/33201532/85437541-5bf2e680-b5a8-11ea-8caf-96cd29afbbf2.gif" height="400" />

**Comment by chapulina** [comment]
I haven't looked closely at the source code in this repository yet. But let me see if I can help you with some pointers.

> I believe this can be avoided to a great extent and there might be some way to use gui::Plugin

Yes, absolutely right. Ignition GUI has been designed with the goal of loading `ignition::gui::Plugin`s. You are encouraged to extend that class to add extra functionality, like [ignition::gazebo::gui::GuiSystem](https://github.com/ignitionrobotics/ign-gazebo/blob/master/include/ignition/gazebo/gui/GuiSystem.hh#L44) does.  And I see that your base plugin class is already doing exactly that, so I think that's good.

https://github.com/Sarath18/ign-rviz/blob/2b67463cd1ebd8a85516a830de252dfdf31c6980/ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp#L37

> The visualization plugins at the moment are loaded using pluginlib

I think this library shouldn't concern itself with loading plugins. Ignition GUI is able to load plugins for you and I think you could remove the dependency on `pluginlib`. Not sure if you've tried this, but you could:

1. Install each plugin as a separate `.so` file. I only see 2 libraries installed now, `libign_rviz_common.so` and `libign_rviz_plugins.so`, which I don't think are individual GUI plugins.

2.  Register your plugin install path using [ignition::gui::App()->AddPluginPath()](https://github.com/ignitionrobotics/ign-gui/blob/8144309d57c862f3407dedb648bd4c96631562e2/include/ignition/gui/Application.hh#L125-L127). You should know this at compile time, it will be something like `/path/to/install/ign_rviz_plugins/lib`. This way, Ignition GUI will look for plugins inside that install directory.

3. Load your plugin by passing its library name to [ignition::gui::Add()->LoadPlugin()](https://github.com/ignitionrobotics/ign-gui/blob/8144309d57c862f3407dedb648bd4c96631562e2/include/ignition/gui/Application.hh#L75-L86). For example, if you have the `libTFDisplay.so` library, you can load it passing `TFDisplay`.

I hope this helped :smile:

**Comment by Sarath18** [comment]
Thank you for looking into the issue. 

Yes, I have tried to use `ignition::gui::Plugin` for developing visualization plugins for `ign-rviz`. Loading of the plugin is not the core issue. The reason for the switch from `gui::Plugin` to `pluginlib` was because we don't get back a reference to the plugin that was loaded. The [`LoadPlugin()`](https://github.com/ignitionrobotics/ign-gui/blob/8144309d57c862f3407dedb648bd4c96631562e2/include/ignition/gui/Application.hh#L85-L86) method returns a `bool` and [`PluginList()`](https://github.com/ignitionrobotics/ign-gui/blob/8144309d57c862f3407dedb648bd4c96631562e2/include/ignition/gui/Application.hh#L140-L141) returns a list of names. I want this reference to share the data between the main application and the plugin. 

One of the main reasons for this [architecture](https://github.com/Sarath18/ign-rviz/issues/3#issuecomment-635811612) was to pass a pointer to ROS node, an instance of `FrameManager` along with a few others. Looking at `gui::Plugins` such as `Publisher`, `TopicEcho`, etc. each of them have a `ign::transport` node of their own. I wanted to have a ROS node for the entire application instead of each plugin containing one.

https://github.com/Sarath18/ign-rviz/blob/7504cda51fccb185ab7214d858aea3b97fa8d557/ign_rviz/include/ignition/rviz/rviz.hpp#L75-L77

It will be great to have a method to `gui::Plugin` get back reference to the plugin.
```cpp
plugin::PluginPtr GetPlugin(const std::string & plugin_name)
```
This will help remove the `pluginlib` dependency and get the desired features as well.

**Comment by chapulina** [comment]
>  we don't get back a reference to the plugin that was loaded

Oh, gotcha. There are ways of getting the plugin pointer after loading it though. We've just [been leveraging](https://github.com/ignitionrobotics/ign-gui/blob/master/src/plugins/world_control/WorldControl_TEST.cc#L91) Qt's `findChild` / `findChildren` for that. For example:

```
auto win = App()->findChild<MainWindow *>();
auto worldControlPlugin = win->findChild<plugins::WorldControl *>()
```

(now I'm wondering why not just `App()->findChild<plugins::WorldControl *>()` - I think that may also work)

> It will be great to have a method to gui::Plugin get back reference to the plugin.

Let me know if the `findChild` approach above works for that. I think it should be fine to also add such API to the `gui::Application`, but I think it would be better to use Qt's native functionality whenever we can.

**Comment by Sarath18** [comment]
I think this exactly what I was looking for. Sure, I'll try this out and let your know. Thanks :)
